### ISSUE TITLE
Installation via PIP

### ISSUE THREAD

**Issue by arstropica** [SchynsLab/medusa#3]
Is there an updated wheel file for installation? The documentation references installation via a pip command:

`pip install https://github.com/medusa-4D/medusa/releases/download/v0.0.6/medusa-0.0.6-py3-none-any.whl`

Thank you

**Comment by lukassnoek** [comment]
Hi, yeah sorry, was fixing some tests before actually releasing the v0.0.6 wheel. It's uploaded now the URL has changed (as the repo migrated from the `medusa-4D` org to the `SchynsLab` org):

```
pip install https://github.com/SchynsLab/medusa/releases/download/v0.0.6/medusa-0.0.6-py3-none-any.whl
```

Will update the installation instructions in the docs today.

**Comment by arstropica** [comment]
Thanks!
